### PR TITLE
Sentry

### PR DESCRIPTION
**Pull request by merlinoa**
Added sentry to the front end javascript of polished.  All the user needs to do to add sentry is pass their Sentry.io DSN to the new "sentry_dsn" argument of `global_sessions_config()`.  

I chose to use the Sentry CDN rather than NPM in order to keep our javascript as simple as possible. 

The new "polished_example_04" is an example polished app with Sentry enabled.

### CODE REVIEW

**Comment by phoward38** [comment]
- Installed SDK for tracing bundle locally in `srcjs/src` directory
  - Command: `curl https://browser.sentry-cdn.com/5.27.4/bundle.tracing.min.js -o sentry.browser.5.27.4.tracing.min.js -s`
  - This avoids ad blockers from blocking the CDN, which stopped Sentry from working
- Upgraded SDK version to 5.27.4

**Review by phoward38 — APPROVED** [review]
Upgraded version in local SDK install w/ 901bc29f3cb12ea5a57174e6010cf727d215621c

**Comment by phoward38** [comment]
- Installed SDK for tracing bundle locally in `srcjs/src` directory
  - Command: `curl https://browser.sentry-cdn.com/5.27.4/bundle.tracing.min.js -o sentry.browser.5.27.4.tracing.min.js -s`
  - This avoids ad blockers from blocking the CDN, which stopped Sentry from working
- Upgraded SDK version to 5.27.4

**Comment by merlinoa** [comment]
Awesome.  Nice work on this.  Merging now.

**Pull request merged**
