### PR TITLE
Update/sign in loading

### PR DESCRIPTION
**Pull request by phoward38**
- Added `focus` events, making input focus to `password` when continuing for sign in or register
- Remove loading overlay screen
- Added `tychobratools::loading_button` to replace overlay screen
  - Added JS event (w/ @merlinoa) to `loading_button` (pushed to `tychobratools`) to reset button w/o calling back to R

### CODE REVIEW

**Comment by merlinoa** [comment]
The loading button does not revert to normal after I incorrectly enter my password on the sign in page

**Comment by phoward38** [comment]
- [ ] Fix font size of button
- [ ] Add correct JS resets for register vs. sign in

**Comment by phoward38** [comment]
Fixed. @merlinoa Will need to install newest `tychobratools` for JS reset events to trigger

**Comment by merlinoa** [comment]
@phoward38 works great!

I updated the button styles to make them easier for a user of polished to customize.  Basically I just moved all the inline styles to the "btn-primary" class, so now the user can customize this class to fully control the style of the button.  I also removed the gray background color from the loading button.  IMO it looks better to keep the loading button the same color as the normal button but just add the disabled class coloring effect to show that the button is disabled.  This will work for any user's custom button color.

Can you please go ahead and make the same update to the "no invite required" version of the sign in page, then I think we will be ready to merge.

**Comment by phoward38** [comment]
@merlinoa Completed & added `sign_in_module` as 1st argument in `sign_in_ui_default.R`

**Pull request merged**
