### PR TITLE
Moved toasts to top-center & changed duration to 1 sec

### PR DESCRIPTION
**Pull request by phoward38**
Are you getting these notes from `devtools::check`:
```
> checking package dependencies ... NOTE
  Imports includes 22 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

> checking for future file timestamps ... NOTE
  unable to verify current time
```

### CODE REVIEW

**Review by merlinoa — CHANGES_REQUESTED** [review]
I would define the toast options in 1 location so that you don't need to repeat them over and over.  Also 1 second is much faster than our current showDuration which I think is either 3 or 4 seconds.  Did you test the show duration?

**Comment by phoward38** [comment]
@merlinoa 
- I was thinking the same but wasn't sure where to put the toast options
- Yea I tested it. Our show duration is 0.3 seconds by default in `showToast`

**Comment by merlinoa** [comment]
You can put the toast options in "utils.R".  Use @noRd and don't export them.  

It seemed like our prior default was a lot longer than 0.3 seconds, but I guess it was the fadein and fadeout time.  Anyways update the toast options and I'll check it out real quick.  Thanks.

**Review by merlinoa — APPROVED** [review]

**Comment by merlinoa** [comment]
Awesome! looks good.

**Pull request merged**
